### ISSUE TITLE
Error while trying to create LMDB files by the bash file, OSError

### ISSUE THREAD

**Issue by VanitarNordic** [chenxinpeng/SSD_scene_text_detection#12]
Hello,

I face this error when I run .sh file which uses `create_annoset.py` (Ubuntu 16.04)

```
Traceback (most recent call last):
  File "/home/hesam/Downloads/SDD-Files/SSD-makes/create_annoset.py", line 159, in <module>
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by VanitarNordic** [comment]
The files should be placed inside Caffe Directory

**Comment by le-lshr1214** [comment]
@VanitarNordic ,Hi, which files? where should the files be placed? I face this error too,thanks!

**Comment by VanitarNordic** [comment]
You must run the file from the root, I mean from the caffe-ssd folder
copy it there and run it

**Comment by larryluo619** [comment]
Hello, I have the same error running create_annoset.py. Could you kindly tell me the details you fixed this issue? Which files should be copied and run under caffe root folder?
Thanks!

**Comment by lwzeng** [comment]
I also encountered the same error. I found that because I used clion to compile caffe, so I need to change cmd = "{}/build/tools/convert_annoset"\ to cmd = "{ }/cmake-build-release/tools/convert_annoset" \ in caffe/script/create_annoset.py

**Comment by qaz3014** [comment]
Check your convert_annoset.exe path in caffe/script/create_annoset.py should solve the problem.
